name: MLDL-Neptune
channels:
    - defaults
    - conda-forge
dependencies:
    - python=3.8
    - numpy=1.19
    - pandas=1.1
    - neptune-client
    - psutil
    - scikit-learn 
    - matplotlib
    - seaborn
    - pip
#    - tensorflow-gpu
#    - catboost
#    - xgboost
    - notebook
